[package]
name = "gb_emulator"
version = "0.1.0"
authors = ["Victor Fordham"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.2.0"